#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    triggers { pollSCM('* * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20'))
        timestamps()
    }
    stages {

        stage("create docker image") {
            steps {
                echo " ============== start bulding image =================="
                dir ('docker/toolbox'){
                sh 'docker build .'
                }
            }
        }
    }
}
